import { LeadershipRole } from "../types/leadership";

export const LEADERSHIP = {
  title: "Pastors and Directors",
  subtitle: "Leadership",
  description: "Meet our dedicated leaders serving the church and community.",
  PASTORS: [
    {
      id: "1",
      name: "Pastor Abel Ukweni",
      title: "Resident Pastor",
      role: LeadershipRole.RESIDENT_PASTOR,
      bio: "Pastor Abel Ukweni has been serving as Resident Pastor of WCI Goderich since 2015. With over 15 years of ministry experience, he is passionate about teaching God's Word and building strong believers. He holds a Master's degree in Theology and is known for his practical and inspiring messages.",
      image:
        "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=826&h=1239&fit=crop&q=80",
      email: "pastor.abel@wcigoderich.org",
      phone: "+232 88 123 456",
      education: [
        "Master of Theology - Living Faith Bible College",
        "Bachelor of Divinity - Sierra Leone Theological College",
        "Certificate in Pastoral Ministry - International Bible Institute",
      ],
      experience: [
        "Resident Pastor - WCI Goderich (2015-Present)",
        "Associate Pastor - WCI Freetown (2010-2015)",
        "Youth Pastor - WCI Bo (2008-2010)",
        "Ministry Intern - WCI Kenema (2006-2008)",
      ],
      specialties: [
        "Biblical Teaching",
        "Leadership Development",
        "Pastoral Care",
        "Church Growth",
        "Prayer Ministry",
      ],
      socialMedia: {
        facebook: "https://facebook.com/pastorabelukweni",
        twitter: "https://twitter.com/pastorabelukweni",
        instagram: "https://instagram.com/pastorabelukweni",
      },
      featured: true,
      ordinationDate: "2008",
      yearsInMinistry: 16,
    },
    {
      id: "2",
      name: "Pastor Lungay Sellu",
      title: "Associate Pastor",
      role: LeadershipRole.ASSOCIATE_PASTOR,
      bio: "Pastor Lungay Sellu serves as our Associate Pastor, focusing on women's ministry and family counseling. She brings a heart for nurturing and discipleship, having served in ministry for over 12 years.",
      image:
        "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=826&h=1239&fit=crop&q=80",
      email: "pastor.lungi@wcigoderich.org",
      phone: "+232 88 123 457",
      education: [
        "Master of Divinity - Sierra Leone Theological College",
        "Bachelor of Christian Education - Living Faith Bible College",
        "Certificate in Counseling - International Christian Counseling Institute",
      ],
      experience: [
        "Associate Pastor - WCI Goderich (2018-Present)",
        "Women's Ministry Director - WCI Freetown (2015-2018)",
        "Children's Pastor - WCI Bo (2012-2015)",
        "Ministry Coordinator - WCI Kenema (2010-2012)",
      ],
      specialties: [
        "Women's Ministry",
        "Family Counseling",
        "Children's Ministry",
        "Discipleship",
        "Pastoral Care",
      ],
      socialMedia: {
        facebook: "https://facebook.com/pastorlungikamara",
        instagram: "https://instagram.com/pastorlungikamara",
      },
      featured: true,
      ordinationDate: "2012",
      yearsInMinistry: 12,
    },
  ] as const,
  LEADERS: [
    {
      id: "1",
      name: "Elder David Thompson",
      title: "Church Elder",
      role: LeadershipRole.ELDER,
      department: "Leadership",
      bio: "Elder David Thompson has been a faithful member of our church for over 20 years and serves as a spiritual leader and advisor to the pastoral team.",
      image:
        "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=826&h=1239&fit=crop&q=80",
      email: "elder.david@wcigoderich.org",
      responsibilities: [
        "Spiritual oversight",
        "Pastoral support",
        "Church discipline",
        "Leadership development",
      ],
      featured: true,
    },
    {
      id: "2",
      name: "Deacon Grace Williams",
      title: "Head Deacon",
      role: LeadershipRole.DEACON,
      department: "Service",
      bio: "Deacon Grace Williams leads our deacon board and oversees various service ministries within the church.",
      image:
        "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=826&h=1239&fit=crop&q=80",
      email: "deacon.grace@wcigoderich.org",
      responsibilities: [
        "Deacon board leadership",
        "Service coordination",
        "Member care",
        "Ministry support",
      ],
      featured: true,
    },
    {
      id: "3",
      name: "Sister Maria Rodriguez",
      title: "Worship Director",
      role: LeadershipRole.WORSHIP_DIRECTOR,
      department: "Worship",
      bio: "Sister Maria Rodriguez leads our worship ministry, bringing excellence and anointing to our praise and worship services.",
      image:
        "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=826&h=1239&fit=crop&q=80",
      email: "worship.maria@wcigoderich.org",
      responsibilities: [
        "Worship team leadership",
        "Music ministry coordination",
        "Worship service planning",
        "Musical training",
      ],
      featured: true,
    },
    {
      id: "4",
      name: "Brother James Wilson",
      title: "Men's Ministry Leader",
      role: LeadershipRole.MINISTRY_LEADER,
      department: "Ministry",
      bio: "Brother James Wilson leads our men's ministry, focusing on spiritual growth, accountability, and leadership development among men.",
      image:
        "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&h=1200&fit=crop&q=80",
      email: "mens.james@wcigoderich.org",
      responsibilities: [
        "Men's fellowship coordination",
        "Leadership development",
        "Mentorship programs",
        "Men's events planning",
      ],
      featured: false,
    },
    {
      id: "5",
      name: "Sister Lisa Anderson",
      title: "Children's Ministry Director",
      role: LeadershipRole.DIRECTOR,
      department: "Ministry",
      bio: "Sister Lisa Anderson leads our children's ministry, creating engaging and educational programs for children of all ages.",
      image:
        "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=800&h=1200&fit=crop&q=80",
      email: "children.lisa@wcigoderich.org",
      responsibilities: [
        "Children's ministry coordination",
        "Sunday school oversight",
        "Children's events planning",
        "Volunteer training",
      ],
      featured: true,
    },
  ] as const,
  DIRECTORS: [
    {
      id: "3",
      name: "Pastor Michael Chen",
      title: "Chairman Board of Directors",
      role: LeadershipRole.CHAIRMAN,
      bio: "Pastor Michael Chen serves as Chairman of the Board of Directors, providing strategic leadership and governance oversight for WCI Goderich. With extensive experience in organizational leadership and church administration, he ensures the church operates with integrity, vision, and accountability while supporting the pastoral team in fulfilling the church's mission.",
      image:
        "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=826&h=1239&fit=crop&q=80",
      email: "pastor.michael@wcigoderich.org",
      phone: "+232 88 123 458",
      education: [
        "Master of Divinity - Sierra Leone Theological College",
        "Bachelor of Business Administration - University of Sierra Leone",
        "Certificate in Church Administration - International Bible Institute",
        "Diploma in Leadership and Governance - Christian Leadership Institute",
      ],
      experience: [
        "Chairman Board of Directors - WCI Goderich (2020-Present)",
        "Board Member - WCI Freetown (2018-2020)",
        "Church Administrator - WCI Bo (2016-2018)",
        "Leadership Team Member - WCI Kenema (2014-2016)",
      ],
      specialties: [
        "Strategic Planning",
        "Church Governance",
        "Organizational Leadership",
        "Financial Oversight",
        "Board Development",
      ],
      socialMedia: {
        facebook: "https://facebook.com/pastormichaelchen",
        instagram: "https://instagram.com/pastormichaelchen",
        tiktok: "https://tiktok.com/@pastormichaelchen",
      },
      featured: true,
      ordinationDate: "2014",
      yearsInMinistry: 10,
    },
  ] as const,
};
