import type { PrayerGroup, PrayerPoint, PrayerSession } from "@/lib/types/prayer";

export const PRAYER_GROUPS: PrayerGroup[] = [
  {
    id: "midnight-1",
    name: "Midnight Prayer Warriors",
    description:
      "A dedicated group that meets weekly at midnight for intensive intercessory prayer. We pray for the church, community, and breakthrough in various areas of life.",
    day: "Fridays",
    time: "12:00 AM",
    location: "Church Auditorium",
    isSpecial: true,
    contactPerson: "Pastor John Doe",
    contactEmail: "prayer@wcigoderich.org",
    contactPhone: "+232 88 123 456",
    maxMembers: 50,
    currentMembers: 32,
  },
  {
    id: "midnight-2",
    name: "Dawn Intercessors",
    description:
      "Early morning prayer group meeting at midnight to usher in the new day with prayer and worship.",
    day: "Tuesdays",
    time: "12:00 AM",
    location: "Online (Zoom)",
    isSpecial: true,
    contactPerson: "Sister Mary Smith",
    contactEmail: "dawn@wcigoderich.org",
    maxMembers: 30,
    currentMembers: 18,
  },
  {
    id: "weekly-1",
    name: "Women's Prayer Circle",
    description:
      "A weekly prayer gathering for women to intercede for families, children, and the community.",
    day: "Wednesdays",
    time: "10:00 AM",
    location: "Church Fellowship Hall",
    contactPerson: "Sister Jane Doe",
    contactEmail: "women@wcigoderich.org",
    maxMembers: 40,
    currentMembers: 25,
  },
  {
    id: "weekly-2",
    name: "Men's Prayer Fellowship",
    description:
      "Men gathering weekly to pray for strength, wisdom, and breakthrough in their lives and families.",
    day: "Thursdays",
    time: "07:00 PM",
    location: "Church Auditorium",
    contactPerson: "Brother James Wilson",
    contactEmail: "men@wcigoderich.org",
    maxMembers: 35,
    currentMembers: 20,
  },
  {
    id: "weekly-3",
    name: "Youth Prayer Force",
    description:
      "Young adults and youth coming together to pray for their generation, education, and future.",
    day: "Saturdays",
    time: "04:00 PM",
    location: "Youth Hall",
    contactPerson: "Pastor Youth Leader",
    contactEmail: "youth@wcigoderich.org",
    maxMembers: 60,
    currentMembers: 45,
  },
];

export const PRAYER_POINTS: PrayerPoint[] = [
  {
    id: "midnight-1",
    title: "Midnight Prayer Points - Breakthrough",
    description:
      "Prayer points for our weekly midnight prayer sessions focusing on breakthrough and victory.",
    category: "midnight",
    points: [
      "Pray for divine breakthrough in every area of stagnation",
      "Ask God to break every chain of limitation and bondage",
      "Pray for open doors and opportunities in career and business",
      "Intercede for financial breakthrough and divine provision",
      "Pray for healing and restoration in families",
      "Ask for wisdom and direction in decision making",
      "Pray for the church and its leadership",
      "Intercede for the nation and its leaders",
    ],
    scripture: "Isaiah 45:2-3 - I will go before you and make the crooked places straight...",
    date: "2025-01-17",
  },
  {
    id: "midnight-2",
    title: "Midnight Prayer Points - Protection",
    description:
      "Prayer points focusing on divine protection and covering for the church and community.",
    category: "midnight",
    points: [
      "Pray for divine protection over the church and its members",
      "Ask God to cover our families with His blood",
      "Intercede for protection during travels and journeys",
      "Pray for protection over our children and youth",
      "Ask for God's shield over our health and wellbeing",
      "Pray for protection of our properties and possessions",
      "Intercede for the nation against evil and destruction",
      "Pray for angelic protection and guidance",
    ],
    scripture: "Psalm 91:1-2 - He who dwells in the secret place of the Most High...",
    date: "2025-01-24",
  },
  {
    id: "general-1",
    title: "General Prayer Points",
    description: "Weekly prayer points for all prayer groups and individuals.",
    category: "general",
    points: [
      "Pray for the church's growth and expansion",
      "Intercede for souls to be saved and lives transformed",
      "Pray for unity and love among believers",
      "Ask for God's favor and blessing on the church",
      "Pray for the pastor and leadership team",
      "Intercede for the community and nation",
      "Pray for provision and financial breakthrough",
      "Ask for healing and restoration",
    ],
    scripture: "1 John 5:14 - This is the confidence we have in approaching God...",
  },
  {
    id: "special-1",
    title: "Special Prayer Points - New Year",
    description: "Prayer points for the new year and new beginnings.",
    category: "special",
    points: [
      "Pray for a year of divine acceleration and progress",
      "Ask God to fulfill all His promises in your life",
      "Intercede for new opportunities and open doors",
      "Pray for divine connections and relationships",
      "Ask for strength and grace to accomplish goals",
      "Pray for protection and preservation throughout the year",
      "Intercede for your family and loved ones",
      "Pray for the church's vision and mandate",
    ],
    scripture: "Isaiah 43:19 - See, I am doing a new thing! Now it springs up...",
    date: "2025-01-01",
  },
];

export const PRAYER_SESSIONS: PrayerSession[] = [
  {
    id: "covenant-hour",
    name: "Covenant Hour of Prayer",
    description:
      "Daily prayer sessions to intercede for the church, community, and personal spiritual growth.",
    day: "Weekdays",
    times: ["06:00 AM"],
    location: "Church Auditorium",
    type: "prayer",
  },
  {
    id: "saturday-prayer",
    name: "Saturday Prayer",
    description: "Weekly Saturday morning prayer session.",
    day: "Saturday",
    times: ["07:00 AM"],
    location: "Church Auditorium",
    type: "prayer",
  },
  {
    id: "midnight-warriors",
    name: "Midnight Prayer Warriors",
    description:
      "Weekly midnight prayer session for intensive intercessory prayer.",
    day: "Fridays",
    times: ["12:00 AM"],
    location: "Church Auditorium",
    type: "group",
    isSpecial: true,
  },
  {
    id: "dawn-intercessors",
    name: "Dawn Intercessors",
    description: "Early morning prayer group meeting at midnight.",
    day: "Tuesdays",
    times: ["12:00 AM"],
    location: "Online (Zoom)",
    type: "group",
    isSpecial: true,
  },
  {
    id: "women-prayer",
    name: "Women's Prayer Circle",
    description: "Weekly prayer gathering for women.",
    day: "Wednesdays",
    times: ["10:00 AM"],
    location: "Church Fellowship Hall",
    type: "group",
  },
  {
    id: "men-prayer",
    name: "Men's Prayer Fellowship",
    description: "Men gathering weekly to pray for strength and breakthrough.",
    day: "Thursdays",
    times: ["07:00 PM"],
    location: "Church Auditorium",
    type: "group",
  },
  {
    id: "youth-prayer",
    name: "Youth Prayer Force",
    description: "Young adults and youth coming together to pray.",
    day: "Saturdays",
    times: ["04:00 PM"],
    location: "Youth Hall",
    type: "group",
  },
];

export const PRAYER_CATEGORIES = [
  { value: "healing", label: "Healing" },
  { value: "provision", label: "Provision" },
  { value: "protection", label: "Protection" },
  { value: "guidance", label: "Guidance" },
  { value: "family", label: "Family" },
  { value: "career", label: "Career" },
  { value: "ministry", label: "Ministry" },
  { value: "salvation", label: "Salvation" },
  { value: "breakthrough", label: "Breakthrough" },
  { value: "other", label: "Other" },
] as const;

